src/main/java/grmlsa/routing/DJK.java, src/main/java/simulationControl/Main.java, src/main/java/simulationControl/parsers/SimulationServer.java
This new feature enable simulations with different simulation servers.
=> enable multi server

src/main/java/grmlsa/modulation/Modulation.java, src/main/java/grmlsa/modulation/ModulationSelector.java, src/main/java/network/PhysicalLayer.java, src/main/java/simulationControl/Main.java, src/main/java/simulationControl/parsers/PhysicalLayerConfig.java, src/main/java/simulator/eventListeners/ArriveRequestForConexionListener.java, src/main/java/simulator/eventListeners/HoldRequestListener.java
Modifications:
- Addition of publication dates of some articles in classes;
- Added the possibility to choose to fixed the power or the power spectral density by circuit;
- Added new physical layer parameters in configuration file.
=> Feature - density or power fixed

src/main/java/measurement/ConsumedEnergy.java, src/main/java/measurement/MetricsOfEnergyConsumption.java, src/main/java/network/EnergyConsumption.java, src/main/java/network/PhysicalLayer.java, src/main/java/simulationControl/resultManagers/MetricsOfEnergyConsumptionResultManager.java
Corrections in the way the general power consumption of the grid was
being computed. Are now counted:
- Average general power consumption;
- Energy efficiency;
- Total data transmitted;
- Total energy consumption by transponders, OXCs and amplifiers.
=> Metrics of the energy consumption

src/main/java/grmlsa/GRMLSA.java, src/main/java/grmlsa/integrated/CompleteSharing.java, src/main/java/grmlsa/integrated/DedicatedPartition.java, src/main/java/grmlsa/integrated/KSPFirstFit.java, src/main/java/grmlsa/integrated/KShortestPathsAndSpectrumAssignment.java, src/main/java/grmlsa/integrated/KShortestPathsComputation.java, src/main/java/grmlsa/integrated/KShortestPathsReductionQoTO.java, src/main/java/grmlsa/integrated/LoadBalancedDedicatedPartition.java, src/main/java/grmlsa/integrated/ModifiedDijkstraPathsComputation.java, src/main/java/grmlsa/integrated/PseudoPartition.java, src/main/java/grmlsa/integrated/ZonePartition.java, src/main/java/grmlsa/integrated/ZonePartitionTopInvasion.java, src/main/java/grmlsa/spectrumAssignment/DispersionAdaptiveFirstLastFit.java, src/main/java/grmlsa/spectrumAssignment/FirstLastExactFit.java, src/main/java/grmlsa/spectrumAssignment/TrafficBalancingSpectrumAssignment.java, src/main/java/network/ControlPlane.java, src/main/java/network/PhysicalLayer.java, src/main/java/network/TranslucentControlPlane.java, src/main/java/simulationControl/Main.java
Added new integrated RMLSA algorithm.
=> Feature new integrated algorithm

src/main/java/network/ControlPlane.java
Changed the method that was called to compute the QoT of an expanded or retracted circuit.
=> Refatoring grooming

src/main/java/network/PhysicalLayer.java
Adjustment of the alpha and beta2 parameters in the physical layer
=> Physical layer adjustment

src/main/java/network/Amplifier.java, src/main/java/network/ControlPlane.java, src/main/java/network/PhysicalLayer.java, src/main/java/network/TranslucentControlPlane.java, src/main/java/simulationControl/parsers/PhysicalLayerConfig.java
Refactoring of the physical layer and addition for the possibility of changing the amplification frequency by the physical layer configuration file.
=> Refactoring the physical layer.

src/main/java/grmlsa/GRMLSA.java, src/main/java/grmlsa/modulation/ModulationSelectionByQoTAndSigma.java
Implemented the modulation selection algorithm based on the KSP-RQoTO algorithm.
=> New modulation selection algorithm

src/main/java/grmlsa/GRMLSA.java, src/main/java/grmlsa/integrated/CompleteSharingEx.java, src/main/java/grmlsa/integrated/KRoutesExpansiveness.java, src/main/java/grmlsa/spectrumAssignment/ExpansivenessFit.java, src/main/java/grmlsa/spectrumAssignment/FirstFitExpansiveness.java, src/main/java/simulationControl/SimulationManagement.java
New KRoutesExpansiveness and CompleteSharingEx integrated RMLSA algorithms.
=> Feature new integrated rmlsa

src/main/java/grmlsa/spectrumAssignment/ExactFit.java, src/main/java/grmlsa/spectrumAssignment/ExpansivenessFit.java, src/main/java/grmlsa/spectrumAssignment/FirstLastExactFit.java
Modified the uses of exact fit in First Last Exact Fit.
=> Modified the implementation of exact fit to conform to the reference.

src/main/java/grmlsa/GRMLSA.java, src/main/java/grmlsa/modulation/ModulationSelectionByQoTv2.java, src/main/java/simulationControl/parsers/SimulationConfig.java
New modulation format selection algorithm
The algorithm tests the most spectrally efficient modulation format until at least the least efficient
=> Feature new modulation algorithm

src/main/java/grmlsa/modulation/Modulation.java, src/main/java/grmlsa/modulation/ModulationSelectionAlgorithmInterface.java, src/main/java/grmlsa/modulation/ModulationSelectionByDistance.java, src/main/java/grmlsa/modulation/ModulationSelectionByDistance2.java, src/main/java/grmlsa/modulation/ModulationSelectionByQoT.java, src/main/java/grmlsa/modulation/ModulationSelectionByQoTAndSigma.java, src/main/java/grmlsa/modulation/ModulationSelectionByQoTv2.java, src/main/java/grmlsa/modulation/ModulationSelector.java, src/main/java/network/ControlPlane.java, src/main/java/network/Mesh.java, src/main/java/network/PhysicalLayer.java
Correction in identification of blocking type
Adjustment in the calculation of the modulation distances
=> Refactoring blocking types

src/main/java/network/Circuit.java, src/main/java/network/ControlPlane.java, src/main/java/network/PhysicalLayer.java
refactoring of the physical layer to allow the implementation of pot allocation algorithm
=> refactoring of the physical layer to power

src/main/java/grmlsa/GRMLSA.java, src/main/java/grmlsa/integrated/CompleteSharingEsPAT.java, src/main/java/grmlsa/integrated/CompleteSharingSSTG.java, src/main/java/grmlsa/trafficGrooming/MTGSR.java, src/main/java/grmlsa/trafficGrooming/MTGSR_SRNP.java, src/main/java/grmlsa/trafficGrooming/MultihopGrooming.java
Bugfix at MTGSR algorithm.
MTGSR was not respecting the virtual hops limit properly.
=> New algorithm iacfqoto

src/main/java/grmlsa/GRMLSA.java, src/main/java/grmlsa/integrated/CompleteSharingEsPAT.java, src/main/java/grmlsa/integrated/CompleteSharingSSTG.java, src/main/java/grmlsa/integrated/KShortestPathsAndSpectrumAssignment.java, src/main/java/grmlsa/integrated/KShortestPathsAndSpectrumAssignment_v2.java, src/main/java/grmlsa/integrated/KShortestPathsComputation.java, src/main/java/grmlsa/integrated/KShortestPathsReductionQoTO.java, src/main/java/grmlsa/integrated/ModifiedDijkstraPathsComputation.java, src/main/java/grmlsa/modulation/ModulationSelectionByQoT.java, src/main/java/grmlsa/modulation/ModulationSelectionByQoTAndSigma.java, src/main/java/grmlsa/modulation/ModulationSelectionByQoTv2.java, src/main/java/grmlsa/regeneratorAssignment/FNSRegeneratorAssignment.java, src/main/java/grmlsa/spectrumAssignment/DispersionAdaptiveFirstLastFit.java, src/main/java/grmlsa/spectrumAssignment/SpectrumAssignmentWithInterferenceReduction.java, src/main/java/grmlsa/trafficGrooming/MTGSR.java, src/main/java/grmlsa/trafficGrooming/MTGSR_SRNP.java, src/main/java/grmlsa/trafficGrooming/MultihopGrooming.java, src/main/java/network/ControlPlane.java, src/main/java/network/PhysicalLayer.java, src/main/java/network/TranslucentControlPlane.java
Adds the method that computes the impact on the SNR of other circuits
=> Feature QoTO impact

src/main/java/grmlsa/integrated/KShortestPathsAndSpectrumAssignment_v2.java, src/main/java/grmlsa/integrated/KShortestPathsReductionQoTO.java, src/main/java/grmlsa/modulation/Modulation.java, src/main/java/grmlsa/spectrumAssignment/SpectrumAssignmentWithInterferenceReduction.java, src/main/java/network/Circuit.java, src/main/java/network/ControlPlane.java, src/main/java/network/EnergyConsumption.java, src/main/java/network/Link.java, src/main/java/network/PhysicalLayer.java, src/main/java/network/TranslucentControlPlane.java, src/main/java/simulationControl/Main.java
Changing the data structure used for the active circuit list. It was switched from TreeSet to a HashSet.
Bandwidth change per bit rate in class modulation.
=> Refactoring data structure

src/main/java/network/Spectrum.java
Reinforcing the verification if the free spectrum is not related to a
guard band
=> Removing unused attributes in the Spectrum Class

src/main/java/grmlsa/KShortestPaths.java, src/main/java/grmlsa/NewKShortestPaths.java, src/main/java/grmlsa/trafficGrooming/MultihopGrooming.java, src/main/java/grmlsa/trafficGrooming/MultihopGroomingSRNP.java, src/main/java/network/ControlPlane.java, src/main/java/util/Grooming.java
Fixing modifications that were applied to the bugfix-grooming-physical-2 branch
=> Fix grooming physical 2

src/main/java/grmlsa/modulation/Modulation.java, src/main/java/grmlsa/modulation/ModulationSelector.java, src/main/java/grmlsa/spectrumAssignment/SpectrumAssignmentWithInterferenceReduction.java, src/main/java/network/ControlPlane.java, src/main/java/network/Mesh.java, src/main/java/network/PhysicalLayer.java, src/main/java/simulationControl/parsers/PhysicalLayerConfig.java
Addition of the number of polarization modes.
Changing the gain setting of the amplifiers.
Adding the bandwidth calculation by the bit rate.
=> Refactoring the physical layer

src/main/java/simulationControl/SimulationFileManager.java, src/main/java/simulationControl/parsers/SimulationRequest.java, src/main/java/simulationControl/resultManagers/ResultManager.java
Removing unused metrics and adding comments to some methods
=> Removing unused metrics
